version: "3.3"

services:

  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
    #  - "8082:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

# Gophish
# https://docs.getgophish.com
  gophish:
    image: "gophish/gophish"
    container_name: "gophish"
    environment:
      - GOPHISH_PUBLIC_IP=""
      - GOPHISH_PUBLIC_PORT=""
      - GOPHISH_INITIAL_ADMIN_PASSWORD=""
      - GOPHISH_MySQL_STRING=""
    ports:
     - 3333:3333
     - 8082:8081
     - 8443:8443
    # - 80:80
    restart: always
    volumes:
      - ./gophish/gophish.db:/app/database/gophish.db
      #- gophish/static/endpoint:/app/static/endpoint
      #- gophish/config.json:/app/config.json
      #- gophish/gophish.crt:/app/admin.crt
      #- gophish/gophish.key:/app/admin.key
      #- gophish/phish.crt:/app/phish.crt
      #- gophish/phish.key:/app/phish.key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gophish.rule=Host(`gophish.localhost`)"
      - "traefik.http.routers.gophish.entrypoints=web"
    networks:
      rfsnet:
        ipv4_address: 10.10.10.2
        
# EvilGinX
  evilginx2:
    image: rfs85dev/evilginx3:3.3.0
    container_name: "evilginx"
    environment:
      - TZ=Europe/London
    ports:
      - 8081:80
      - 9443:443
      - 53:53
    depends_on:
      - gophish
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./app/:/root/.evilginx
      - ./app/phishlets:/app/phishlets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.evilginx.rule=Host(`evilginx.localhost`)"
      - "traefik.http.routers.evilginx.entrypoints=web"
    stdin_open: true
    tty: true
    restart: unless-stopped
    #command: ["/bin/bash"]
    command: ["/bin/evilginx", "-p", "/app/phishlets", "-debug", "-developer"]
    networks:
      rfsnet:
        ipv4_address: 10.10.10.3


  postgres:
    image: "postgres:latest"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - TZ=Europe/London
    networks:
      rfsnet:
        ipv4_address: 10.10.10.4

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 5454:5454/tcp
    environment:
      - PGADMIN_DEFAULT_EMAIL="rfs@rfs.test"
      - PGADMIN_DEFAULT_PASSWORD="RFSRFSRFS"
      - PGADMIN_LISTEN_PORT="5454"
    depends_on:
      - postgres
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"
     - "traefik.http.routers.pgadmin.entrypoints=web"
    networks:
      rfsnet:
        ipv4_address: 10.10.10.5



volumes:
  pgdata:
  data:


networks:
  rfsnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1
